apiVersion: v1
kind: Service
metadata:
  name: chive-frontend
  namespace: chive
  labels:
    app.kubernetes.io/name: chive-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: chive
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chive-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
